# pytest.ini
[pytest]
DJANGO_SETTINGS_MODULE = taxpayer_api.settings.testing
python_files = tests.py test_*.py *_tests.py
addopts = -v --tb=short --strict-markers --reuse-db --create-db
markers =
    slow: slow running tests
    integration: integration tests
    authentication: authentication tests
    db: tests requiring database